---

- name: Check nomad_install_method
  ansible.builtin.fail:
    msg: "nomad_install_method '{{ nomad_install_method }}' not supported"
  when: nomad_install and nomad_install_method not in ['service']


- name: Ensure install nomad
  ansible.builtin.include_tasks: "nomad_install_{{ nomad_install_method }}.yml"
  when: nomad_install

...