---

- name: Ensure {{ nomad_config_path }}
  ansible.builtin.file:
    dest: "{{ nomad_config_path }}"
    state: directory
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"

- name: Ensure dict nomad_ports combined with defaults
  ansible.builtin.set_fact:
    nomad_ports: "{{ nomad_ports | combine(_nomad_ports_defaults) }}"

- name: Ensure dict nomad_server combined with defaults
  ansible.builtin.set_fact:
    nomad_server: "{{ nomad_server | combine(_nomad_server_defaults) }}"

- name: Print nomad_server
  ansible.builtin.debug:
    msg: "nomad_server: {{ nomad_server }}"
    
- name: Ensure nomad base config
  ansible.builtin.template:
    src:   nomad.hcl.j2
    dest:  "{{ nomad_config_path }}/nomad.hcl"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode:  u=rw,g=r
  notify: restart nomad

- name: Ensure nomad client config
  ansible.builtin.template:
    src:           nomad_client.hcl.j2
    dest:          "{{ nomad_config_path }}/nomad_client.hcl"
    owner:         "{{ nomad_user }}"
    group:         "{{ nomad_group }}"
    mode:          u=rw,g=r
    lstrip_blocks: true
  when: nomad_role == 'client'
  notify: restart nomad

- name: Ensure nomad server config
  ansible.builtin.template:
    src:           nomad_server.hcl.j2
    dest:          "{{ nomad_config_path }}/nomad_server.hcl"
    owner:         "{{ nomad_user }}"
    group:         "{{ nomad_group }}"
    mode:          u=rw,g=r
    lstrip_blocks: true
  when: nomad_role == 'server'
  notify: restart nomad

...
