---

- name: Ensure nomad tls cert
  ansible.builtin.shell:
    cmd:     "nomad tls cert create -{{ nomad_role }} -dc {{ nomad_datacenter }} -domain {{ nomad_domain }}{% if nomad_role == 'server' %} -node {{ nomad_node_name }}{% endif %}"
    chdir:   "{{ nomad_tls_path }}"
    creates: "{{ nomad_tls_path }}/{{ nomad_datacenter }}-{{ nomad_role }}-{{ nomad_domain }}-0.pem"

- name: Ensure nomad tls cert group und owner
  ansible.builtin.file:
    path:  "{{ nomad_tls_path }}/{{ nomad_datacenter }}-{{ nomad_role }}-{{ nomad_domain }}-0.pem"
    group: "{{ nomad_group }}"
    owner: "{{ nomad_user }}"

- name: Ensure nomad tls cert key group und owner
  ansible.builtin.file:
    path:  "{{ nomad_tls_path }}/{{ nomad_datacenter }}-{{ nomad_role }}-{{ nomad_domain }}-0-key.pem"
    group: "{{ nomad_group }}"
    owner: "{{ nomad_user }}"

...