---

- name: Ensure Hashicorp key
  ansible.builtin.shell:
    cmd:     wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Ensure Hashicorp repository
  ansible.builtin.shell:
    cmd:echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

- name: Ensure nomad package installed
  ansible.builtin.apt:
    update_cache: true
    name:         "nomad{% if nomad_version != 'latest' %}={{ nomad_version }}{% endif %}"

- name: Ensure nomad service enabled
  ansible.builtin.systemd:
    name:    consul
    enabled: true

- name: Ensure hold nomad package version
  ansible.builtin.dpkg_selections:
    name:      nomad
    selection: hold

...
