---

- name: Ensure nomad tls cert
  ansible.builtin.shell:
    cmd:     "nomad tls cert create -{{ nomad_role }}"
    chdir:   "{{ nomad_tls_path }}"
    creates: "{{ nomad_tls_path }}/global-{{ nomad_role }}-{{ nomad_domain }}.pem"

- name: Ensure nomad tls cert group und owner
  ansible.builtin.file:
    path:  "{{ nomad_tls_path }}/global-{{ nomad_role }}-{{ nomad_domain }}.pem"
    group: "{{ nomad_group }}"
    owner: "{{ nomad_user }}"

- name: Ensure nomad tls cert key group und owner
  ansible.builtin.file:
    path:  "{{ nomad_tls_path }}/global-{{ nomad_role }}-{{ nomad_domain }}-key.pem"
    group: "{{ nomad_group }}"
    owner: "{{ nomad_user }}"

...