---

- name: Ensure {{ nomad_config_path }}
  ansible.builtin.file:
    dest: "{{ nomad_config_path }}"
    state: directory
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"

- name: Ensure dict nomad_ports combined with defaults
  ansible.builtin.set_fact:
    nomad_ports: "{{ _nomad_ports_defaults | combine(nomad_ports) }}"

- name: Ensure dict nomad_server combined with defaults
  ansible.builtin.set_fact:
    nomad_server: "{{ _nomad_server_defaults | combine(nomad_server) }}"

- name: Print nomad_server
  ansible.builtin.debug:
    msg: "nomad_server: {{ nomad_server }}"

- name: Ensure nomad_tls_path
  ansible.builtin.file:
    path:  "{{ nomad_tls_path }}"
    state: directory
    group: "{{ nomad_group }}"
    owner: "{{ nomad_user }}"
    mode:  u=rwx,g=rx,o=x

- name: Ensure nomad tls ca
  ansible.builtin.copy:
    dest:  "{{ nomad_tls_path }}/nomad-agent-ca.pem"
    content: "{{ nomad_tls_ca }}"
    group: "{{ nomad_group }}"
    owner: "{{ nomad_user }}"
    mode:  u=rw,g=r
  when: nomad_tls_ca is defined

- name: Ensure nomad tls ca key
  ansible.builtin.copy:
    dest:  "{{ nomad_tls_path }}/nomad-agent-ca-key.pem"
    content: "{{ nomad_tls_ca_key }}"
    group: "{{ nomad_group }}"
    owner: "{{ nomad_user }}"
    mode:  u=rw,g=r
  when: nomad_tls_ca_key is defined

- name: Ensure nomad base config
  ansible.builtin.template:
    src:   nomad.hcl.j2
    dest:  "{{ nomad_config_path }}/nomad.hcl"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode:  u=rw,g=r
  notify: restart nomad

- name: Ensure nomad client config
  ansible.builtin.template:
    src:           nomad_client.hcl.j2
    dest:          "{{ nomad_config_path }}/nomad_client.hcl"
    owner:         "{{ nomad_user }}"
    group:         "{{ nomad_group }}"
    mode:          u=rw,g=r
    lstrip_blocks: true
  when: nomad_role == 'client'
  notify: restart nomad

- name: Ensure nomad server config
  ansible.builtin.template:
    src:           nomad_server.hcl.j2
    dest:          "{{ nomad_config_path }}/nomad_server.hcl"
    owner:         "{{ nomad_user }}"
    group:         "{{ nomad_group }}"
    mode:          u=rw,g=r
    lstrip_blocks: true
  when: nomad_role == 'server'
  notify: restart nomad

...
